# Crea un archivo para una bd de posgresql con sus variables por defecto
services:
  postgres:
    container_name: postgres-auth
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresdb:/var/lib/postgresql
    ports:
      - 5432:5432
volumes: # Creamos y asignamos el volumen de docker
  postgresdb:
    driver: local
